Feat: Simplify action now that we have a Github App
cto-ai/action pull request #9
Opened 2021-02-18 20:40 UTC by slaterb1

# Overview
Main flow of events is handled via The Ops Platform Workflow Agent Github App. This update extends the insights returned by the Github App by allowing users to specify additional events they care about and deployments.

2021-02-18 21:19 UTC, lucamaraschi approved these changes
Code looks really good

2021-02-18 22:24 UTC, slajax requested changes

2021-02-18 22:24 UTC, kc-dot-io commented on README.md
> +This Github Action allows you to extend the insights data received by the Ops Platform Github App. You can add data to you workflows for deployment tools that are not configured with Github's deploym
Let's remove "the Ops Platform" and just say "CTO.ai".

2021-02-18 22:24 UTC, kc-dot-io commented on README.md
> +**Required** Ops Platform api token, follow [these docs to generate](https://cto.ai/docs/integrate-any-tool)
Let's remove "the Ops Platform" and just say "CTO.ai".

2021-02-18 22:24 UTC, kc-dot-io commented on README.md
> +**Required** Ops Platform team ID sending the data, follow [these docs to access](https://cto.ai/docs/integrate-any-tool)
Let's remove "the Ops Platform" and just say "CTO.ai".

2021-02-18 22:24 UTC, slajax commented
All the functionality LGTM, couple cosmetic comments about branding.

2021-02-19 00:03 UTC, slajax approved these changes

2021-02-19 01:37 UTC, merged